apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: hello-gitops-app
  newName: docker.io/ooocamel/hello-gitops
  newTag: 5d6d744f5637433ddfc57ccd8fe5593034f4aa3b
